import type { Metadata } from "next";
import "bootstrap/dist/css/bootstrap.min.css";
import { Inter } from "next/font/google";
import "./globals.css";
import Page_links from "./links/page";
import Providers from "@/app/redux/providers";
import Footer from "./footer/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Sample Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* Links for  all pages . you can see it from links directory */}
        <Page_links />
        {/* provider from redux provider  */}
        <Providers> {children} </Providers>
        {/* footer section ,that will appear in all pages  */}
        <Footer />
      </body>
    </html>
  );
}
